[defaults]
template_type = "python"

[output.".ctt/python"]
docker = true

[output.".ctt/django-simple"]
template_type = "django"
ui = false
rest = false
gis = false

[output.".ctt/django-rest"]
template_type = "django"
rest = true
ui = false

[output.".ctt/django-gis"]
template_type = "django"
ui = false
rest = false
gis = true

[output.".ctt/django-ui"]
template_type = "django"
ui = true
rest = false
gis = false

[output.".ctt/django-full"]
template_type = "django"
ui = true
rest = true
gis = true
