[defaults]
template_type = "python"

[output.".ctt/defaults"]

[output.".ctt/django-full"]
gis = true
rest = true
template_type = "django"
ui = true

[output.".ctt/django-gis"]
gis = true
rest = false
template_type = "django"
ui = false

[output.".ctt/django-rest"]
rest = true
template_type = "django"
ui = false

[output.".ctt/django-simple"]
gis = false
rest = false
template_type = "django"
ui = false

[output.".ctt/django-ui"]
gis = false
rest = false
template_type = "django"
ui = true

[output.".ctt/python"]
docker = true
